name: Terraform Provide

on:
  workflow_dispatch:
  repository_dispatch:
    types: [provide]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd docker && terraform init

      - name: Terraform Plan
        run: cd docker && terraform plan

      - name: Terraform Apply
        run: cd docker && terraform apply -auto-approve
